version: '3'

networks:
  kafkanetwork:
    name: kafka-network
    external: true

services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    networks:
      - kafkanetwork
    environment:
      KAFKA_CLUSTERS_0_NAME: Axiom-1
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:29092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schemaregistry0:8085
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect0:8083
      KAFKA_CLUSTERS_1_NAME: Axiom-2
      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: kafka1:29093
      KAFKA_CLUSTERS_1_METRICS_PORT: 9998
      KAFKA_CLUSTERS_1_SCHEMAREGISTRY: http://localhost:8085
      KAFKA_CLUSTERS_2_NAME: Axiom-3
      KAFKA_CLUSTERS_2_BOOTSTRAPSERVERS: kafka2:29094
      KAFKA_CLUSTERS_2_METRICS_PORT: 9999
      KAFKA_CLUSTERS_2_SCHEMAREGISTRY: http://localhost:8085
      DYNAMIC_CONFIG_ENABLED: 'true'